[package]
name = "toy_in_rust"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["main", "machine"]

[dependencies]
regex = "1.0"
hex = "0.4"
num-traits = "0.2"
num-derive = "0.3"
num = "0.3"
